app = "<YOUR_APP_NAME>"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "vaultwarden/server:latest"

[env]
  WEBSOCKET_ENABLED = "true"
  SIGNUPS_ALLOWED = "false"
  DOMAIN = "https://<YOUR_APP_NAME>.fly.dev"

[mounts]
  source="vaultwarden_data"
  destination="/data"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
